version: 1
license_key: "li87Dd96Dh8zG/(c7g7)CGs70hihhhi/GkBfubumö"
billing:
    currency: "€"
csv_files: 
    categories: 
        - ID
        - NAME
    products:
        - ID
        - NAME
        - PRICE
        - CATEGORY_ID
    customers:
        - ID
        - NAME
        - EMAIL
        - PASS_WORD
messages: {
    "EN": {
        "what_to_order": "What do want to order? Enter a number from above.",
        "msr": "pcs.",
        "how_many": "How many?",
        "unrecognized_input": "Leider haben wir keinen Übersetzer gefunden, der diese Anweisung überesetzen kann.."
    },
    "DE": {
        "what_to_order": "Was möchten Sie bestellen? (Nummer s. oben). Geben Sie 0 ein, wenn Sie die Bestellung abschließen wollen.",
        "msr": "Stück",
        "how_many": "Wie viele?",
        "unrecognized_input": "{} bieten wir leider nicht an.. Wollen Sie weiter bestellen ('w') oder haben Sie fertig (ENTER)?\n>"
    }
}
output_management:
    output_file_directory: "out"